CREATE DATABASE IF NOT EXISTS devbook;

use devbook;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS  users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    nickname VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(80) NOT NULL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) ENGINE=INNODB;
